### ISSUE TITLE
#US09 Como usuario quiero registrarme en el Sitio Web

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#110]

**Comment by Romherre** [comment]
El compañero Ignacio creo el código necesario para que el usuario puede registrarse y loguearse en la web. 
Logrando conectar el front con el Backend
Agregando las validaciones necesitaría para que el usuario pueda ser advertido en el caso de colocar un dato erróneo
