### ISSUE TITLE
Scrum Master

### ISSUE THREAD

**Issue by Leo-Farran** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#124]
Definir Scrum Master inicial. Aclarar y acordar modalidad de trabajo

**Comment by Romherre** [comment]
Los que continuamos en el grupo decidimos que el compañero Ignacio Carnero sea el nuevo Scrum Master. El año pasado hizo un muy buen trabajo y consideramos que era la mejor persona para ser el lider de KILLCODE. En la primer reunion nos explico la modalidad de trabajo para el buen desarrollo del proyecto. Y en varias ocaciones nos ayudo con problemas especificos a cada uno sin dejar de lado el desarrollo de sus tareas. Agradecidos con el compañero. Se cierra tarea
