### ISSUE TITLE
Tablero de control para usuarios: Mostrar catálogo (mínimo 3 productos o servicios o suscripción). Seleccionar para comprar.

### ISSUE THREAD

**Issue by Leo-Farran** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#128]
Crear vista de servicios ofrecidos

**Comment by Romherre** [comment]
En nuestro caso mostramos los servicios como paquetes para que el usuario seleccione y pueda comprar el paquete que sea acordé a su necesidad
