### ISSUE TITLE
Convertir los archivos .html del proyecto previo, en una SPA en Angular con módulos.

### ISSUE THREAD

**Issue by Leo-Farran** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#129]
Generar estructura de modulos para el directorio de archivos

**Comment by Romherre** [comment]
Durante el sprint nos dedicamos adaptar el proyecto del año pasado desarrollado con HTML, Bootstrap, css y JavaScript utilizando Angular y su estructura basada en módulos y componentes. Además nos enfocamos en aprender typescript .
Hemos aprendido mucho y nos ayudamos a lograr este objetivo mutuamente. Estamos contentos con el resultado.
