### ISSUE TITLE
Diagramas backend

### ISSUE THREAD

**Issue by Leo-Farran** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#130]
Diseño conceptual al que ya hemos visto como DER: Diagrama Entidad-Relación.
Diseño Lógico que consta de la Normalización y el Modelo Relacional.

**Comment by Romherre** [comment]
Gracias al desarrollo del año pasado donde aprendimos el uso de base datos, los diagramas, etc. Cuando iniciamos el nuevo año solo tuvimos que realizar unas pequeñas modificaciones para adaptarlas a las mejoras del proyecto. 
Se cierra tarea
