### ISSUE TITLE
Componentes necesarios

### ISSUE THREAD

**Issue by Leo-Farran** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#132]
Crear componentes: HOME, REGISTRO, LOGIN, DASHBOARD. Requerimiento de proyecto.

**Comment by Romherre** [comment]
Con los compañeros hemos logrado cumplir los requerimientos para migrar el proyecto a Angular en forma exitosa. Creando los componentes solicitados y los acordes a el proyecto que desarrollamos.
