### ISSUE TITLE
#TK Data binding

### ISSUE THREAD

**Issue by Leo-Farran** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#134]
Inyectar a los componentes los correspondientes servicios a fin de que los componentes puedan acceder a los datos y mostrarlos en pantalla. Incluye enlace de datos (Data binding).

**Comment by Romherre** [comment]
Tarea completada el compañero Leonardo Farran a logrado conectar el formulario registro de empleados con la base de datos para que el usuario no solo pueda cargar, borrar , actualizar un dato sino que pueda observar cada uno de los cambios dentro de la web.
