### ISSUE TITLE
#TK04 Migrar el proyecto a Angular

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#15]

**Comment by Romherre** [comment]
Durante el sprint nos dedicamos adaptar el proyecto del año pasado desarrollado con HTML, Bootstrap, css y JavaScript utilizando Angular y su estructura basada en módulos y componentes. Además nos enfocamos en aprender typescript .
Hemos aprendido mucho y nos ayudamos a lograr este objetivo mutuamente. Estamos contentos con el resultado.
