### ISSUE TITLE
#TK06 Registrar meetings del Sprint 0

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#17]

**Comment by Romherre** [comment]
Se registraron cada uno de los meetings consideramos que las reuniones fueron enriquecedoras y nos ayudaron  superar los problemas que se iban presentando a medida que avanzamos con el desarrollo. 
Excelente grupo el trato fue muy amable y siempre las sugerencias fueron para mejorar. 
Los meeting los encontraran en la wiki
