### ISSUE TITLE
#TK09 Componente Carrito Compras

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#27]

**Comment by Leo-Farran** [comment]
Se desarrolla lógica de botones del carrito de compras. Se agrega botón de carrito el cual despliega modal. Se utilizan observables para manejo de comportamiento de servicios agregados al carrito. Se desarrolla lógica para conexión con API de rest_framework de Django. Se agrega mensajes de confirmación y error según corresponda. Se verifica registro exitoso en tabla databasemanager_pedido
