### ISSUE TITLE
#TK02 Revisar Maquetado del Proyecto

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/E-COMMERCE-ISPC-KILL-CODE#5]

**Comment by Romherre** [comment]
Cada uno de los compañeros durante las vacaciones realizo diferentes cursos  y con esos conocimientos este año decidimos mejorar el maquetado del proyecto. 
La incorporación en el grupo de Leonardo Farran y Andres Torrez fue una muy buena decisión ya que al mirar con otros ojos el proyecto logramos hacer mejoras para que el usuario tenga una mejor experiencia. 
Cada uno de nosotros presento un maquetado, sugirió colores, tipografías etc logrando un acuerdo para que el sitio se visualice como actualmente se presenta.
